# Generated by Django 4.2.4 on 2023-08-25 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jspider',
            fields=[
                ('course_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mob', models.IntegerField()),
                ('doj', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jspider')),
            ],
        ),
    ]
